In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [19]:
data=pd.read_csv('EmployeeAttrition.csv')

In [13]:
data.shape

(1470, 14)

In [20]:
data.describe()

JobLevel  DailyRate(USD)  MonthlyIncome(USD)  NoofCompaniesWorked  \
count  1470.000000     1470.000000         1466.000000          1470.000000   
mean      2.063946      802.485714         6503.751023             2.693197   
std       1.106940      403.509100         4710.393079             2.498009   
min       1.000000      102.000000         1009.000000             0.000000   
25%       1.000000      465.000000         2911.000000             1.000000   
50%       2.000000      802.000000         4919.000000             2.000000   
75%       3.000000     1157.000000         8379.000000             4.000000   
max       5.000000     1499.000000        19999.000000             9.000000   

       TotalWorkingYears  YearsAtCompany  YearsInCurrentRole  \
count        1470.000000     1470.000000         1470.000000   
mean           11.279592        7.008163            4.229252   
std             7.780782        6.126525            3.623137   
min             0.000000        0.000000            0.000000   
25%             6.000000        3.000000            2.000000   
50%            10.000000        5.000000            3.000000   
75%            15.000000        9.000000            7.000000   
max            40.000000       40.000000           18.000000   

       YearsSinceLastPromotion  YearsWithCurrentManager  TrainingTimesLastYear  
count              1470.000000              1470.000000            1470.000000  
mean                  2.187755                 4.123129               2.799320  
std                   3.222430                 3.568136               1.289271  
min                   0.000000                 0.000000               0.000000  
25%                   0.000000                 2.000000               2.000000  
50%                   1.000000                 3.000000               3.000000  
75%                   3.000000                 7.000000               3.000000  
max                  15.000000                17.000000               6.000000

In [21]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 14 columns):
Education                  1470 non-null object
JobInvolvement             1466 non-null object
JobLevel                   1470 non-null int64
DailyRate(USD)             1470 non-null int64
MonthlyIncome(USD)         1466 non-null float64
NoofCompaniesWorked        1470 non-null int64
TotalWorkingYears          1470 non-null int64
YearsAtCompany             1470 non-null int64
YearsInCurrentRole         1470 non-null int64
YearsSinceLastPromotion    1470 non-null int64
YearsWithCurrentManager    1470 non-null int64
TrainingTimesLastYear      1470 non-null int64
PerformanceRating          1470 non-null object
Attrition                  1470 non-null object
dtypes: float64(1), int64(9), object(4)
memory usage: 160.9+ KB


In [22]:
data.isnull().sum()

Education                  0
JobInvolvement             4
JobLevel                   0
DailyRate(USD)             0
MonthlyIncome(USD)         4
NoofCompaniesWorked        0
TotalWorkingYears          0
YearsAtCompany             0
YearsInCurrentRole         0
YearsSinceLastPromotion    0
YearsWithCurrentManager    0
TrainingTimesLastYear      0
PerformanceRating          0
Attrition                  0
dtype: int64

In [23]:
data['MonthlyIncome(USD)']=data['MonthlyIncome(USD)'].fillna(data['MonthlyIncome(USD)'].median())

In [24]:
data

Education JobInvolvement  JobLevel  DailyRate(USD)  \
0           College           High         2            1102   
1     Below College         Medium         2             279   
2           College         Medium         1            1373   
3            Master           High         1            1392   
4     Below College           High         1             591   
5           College           High         1            1005   
6          Bachelor      Very High         1            1324   
7     Below College           High         1            1358   
8          Bachelor            NaN         3             216   
9          Bachelor           High         2            1299   
10         Bachelor      Very High         1             809   
11          College         Medium         2             153   
12    Below College           High         1             670   
13          College           High         1            1346   
14         Bachelor         Medium         1             103   
15           Master      Very High         3            1389   
16          College      Very High         1             334   
17          College      Very High         1            1123   
18           Master         Medium         4            1219   
19         Bachelor           High         1             371   
20          College      Very High         2             673   
21           Master         Medium         1            1218   
22           Master            NaN         3             419   
23          College           High         1             391   
24    Below College           High         1             699   
25         Bachelor           High         5            1282   
26    Below College            NaN         1            1125   
27           Master           High         2             691   
28           Master            NaN         3             477   
29           Master           High         5             705   
...             ...            ...       ...             ...   
1440        College           High         2             688   
1441         Master           High         2             667   
1442         Master           High         1            1092   
1443       Bachelor           High         5             300   
1444        College           High         1             310   
1445         Master         Medium         4             582   
1446       Bachelor         Medium         2             704   
1447         Master            Low         2             301   
1448       Bachelor         Medium         2             930   
1449       Bachelor           High         1             529   
1450         Master           High         3            1146   
1451        College           High         2             345   
1452         Master           High         2             878   
1453         Master         Medium         2            1120   
1454       Bachelor           High         2             374   
1455         Master         Medium         1            1322   
1456         Master           High         2            1199   
1457         Master           High         1            1194   
1458         Master            Low         1             287   
1459        College         Medium         2            1378   
1460         Master         Medium         1             468   
1461       Bachelor         Medium         3             410   
1462  Below College         Medium         4             722   
1463       Bachelor           High         2             325   
1464       Bachelor         Medium         1            1167   
1465        College      Very High         2             884   
1466  Below College         Medium         3             613   
1467       Bachelor      Very High         2             155   
1468       Bachelor         Medium         2            1023   
1469       Bachelor      Very High         2             628   

      MonthlyIncome(USD)  NoofCompaniesWo

In [25]:
data['JobInvolvement'].value_counts()

High         867
Medium       373
Very High    144
Low           82
Name: JobInvolvement, dtype: int64

In [26]:
print(data['JobInvolvement'].value_counts())
data['JobInvolvement']=data['JobInvolvement'].replace(['High','Medium','Very High','Low'],[0,2,3,1])
print(data['JobInvolvement'].value_counts())

High         867
Medium       373
Very High    144
Low           82
Name: JobInvolvement, dtype: int64
0.0    867
2.0    373
3.0    144
1.0     82
Name: JobInvolvement, dtype: int64


In [27]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
print(data['JobInvolvement'].value_counts())
data['JobInvolvement']=le.fit_transform(data['JobInvolvement'])
print(data['JobInvolvement'].value_counts())

0.0    867
2.0    373
3.0    144
1.0     82
Name: JobInvolvement, dtype: int64
0    867
2    373
3    144
1     82
7      1
6      1
5      1
4      1
Name: JobInvolvement, dtype: int64


In [28]:
data.head()

Education  JobInvolvement  JobLevel  DailyRate(USD)  \
0        College               0         2            1102   
1  Below College               2         2             279   
2        College               2         1            1373   
3         Master               0         1            1392   
4  Below College               0         1             591   

   MonthlyIncome(USD)  NoofCompaniesWorked  TotalWorkingYears  YearsAtCompany  \
0              5993.0                    8                  8               6   
1              5130.0                    1                 10              10   
2              2090.0                    6                  7               0   
3              2909.0                    1                  8               8   
4              3468.0                    9                  6               2   

   YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrentManager  \
0                   4                        0                        5   
1                   7                        1                        7   
2                   0                        0                        0   
3                   7                        3                        0   
4                   2                        2                        2   

   TrainingTimesLastYear PerformanceRating Attrition  
0                      0         Excellent       Yes  
1                      3       Outstanding        No  
2                      3         Excellent       Yes  
3                      3         Excellent        No  
4                      3         Excellent        No

In [29]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
print(data["Education"].value_counts())
data['Education']=le.fit_transform(data['Education'])
print(data['Education'].value_counts())

Bachelor         572
Master           398
College          282
Below College    170
Doctor            48
Name: Education, dtype: int64
0    572
4    398
2    282
1    170
3     48
Name: Education, dtype: int64


In [30]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
print(data['JobInvolvement'].value_counts())
data['JobInvolvement']=le.fit_transform(data['JobInvolvement'])
print(data['JobInvolvement'].value_counts())

0    867
2    373
3    144
1     82
7      1
6      1
5      1
4      1
Name: JobInvolvement, dtype: int64
0    867
2    373
3    144
1     82
7      1
6      1
5      1
4      1
Name: JobInvolvement, dtype: int64


In [32]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
print(data['PerformanceRating'].value_counts())
data['PerformanceRating']=le.fit_transform(data['PerformanceRating'])
print(data['PerformanceRating'].value_counts())

0    1244
1     226
Name: PerformanceRating, dtype: int64
0    1244
1     226
Name: PerformanceRating, dtype: int64


In [33]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
print(data['Attrition'].value_counts())
data['Attrition']=le.fit_transform(data['Attrition'])
print(data['Attrition'].value_counts())

No     1233
Yes     237
Name: Attrition, dtype: int64
0    1233
1     237
Name: Attrition, dtype: int64


In [144]:
data.head()

Education  JobInvolvement  JobLevel  DailyRate(USD)  MonthlyIncome(USD)  \
0          2               0         2            1102              5993.0   
1          1               0         2             279              5130.0   
2          2               0         1            1373              2090.0   
3          4               0         1            1392              2909.0   
4          1               0         1             591              3468.0   

   NoofCompaniesWorked  TotalWorkingYears  YearsAtCompany  YearsInCurrentRole  \
0                    8                  8               6                   4   
1                    1                 10              10                   7   
2                    6                  7               0                   0   
3                    1                  8               8                   7   
4                    9                  6               2                   2   

   YearsSinceLastPromotion  YearsWithCurrentManager  TrainingTimesLastYear  \
0                        0                        5                      0   
1                        1                        7                      3   
2                        0                        0                      3   
3                        3                        0                      3   
4                        2                        2                      3   

   PerformanceRating  Attrition  
0                  0          1  
1                  1          0  
2                  0          1  
3                  0          0  
4                  0          0

In [34]:
x2=data.iloc[:,[0,2,4,5,11,12]]
x2.head()

Education  JobLevel  MonthlyIncome(USD)  NoofCompaniesWorked  \
0          2         2              5993.0                    8   
1          1         2              5130.0                    1   
2          2         1              2090.0                    6   
3          4         1              2909.0                    1   
4          1         1              3468.0                    9   

   TrainingTimesLastYear  PerformanceRating  
0                      0                  0  
1                      3                  1  
2                      3                  0  
3                      3                  0  
4                      3                  0

In [35]:
y=data.iloc[:,[13]]
y.head()

Attrition
0          1
1          0
2          1
3          0
4          0

In [36]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x2,y,test_size=0.2,random_state=0)

In [37]:
print(x_train.shape)
print(x_test.shape)

(1176, 6)
(294, 6)


In [38]:
print(y_train.shape)
print(y_test.shape)

(1176, 1)
(294, 1)


In [39]:
from sklearn.feature_selection import mutual_info_classif
mi=mutual_info_classif(x_train,y_train)
mi

C:\Users\91944\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0.        , 0.02857671, 0.04286744, 0.01043086, 0.        ,
       0.00656763])

In [40]:
MI=pd.Series(mi)
MI.index=x_train.columns
MI.sort_values(ascending=False)

MonthlyIncome(USD)       0.042867
JobLevel                 0.028577
NoofCompaniesWorked      0.010431
PerformanceRating        0.006568
TrainingTimesLastYear    0.000000
Education                0.000000
dtype: float64

In [41]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [42]:
y_test[:5]

Attrition
442           0
1091          0
981           1
785           0
1332          1
501           0
1058          1
1253          0
751           0
122           1
268           0
940           1
1125          0
540           1
1034          0
432           0
794           0
666           1
942           0
1114          0
853           0
1330          0
692           0
548           0
54            0
319           0
1147          0
1235          0
1436          0
520           0
...         ...
322           0
742           0
935           0
479           1
1236          1
1079          0
461           0
58            0
241           0
1103          0
783           0
1399          0
56            0
665           0
575           0
505           0
443           1
1283          0
516           0
29            0
270           0
924           0
1288          0
985           1
1327          0
1439          0
481           0
124           1
198           0
1229          0

[294 rows x 1 columns]

In [46]:
y_pred=lr.predict(x_test)
y_pred[:5]

array([[0.05619646],
       [0.17863361],
       [0.15255455],
       [0.03410831],
       [0.19292511]])

In [47]:
from sklearn.metrics import r2_score
r2_score(y_pred,y_test)

-23.06412303605954

In [48]:
from sklearn.linear_model import LogisticRegression
logr=LogisticRegression()
logr.fit(x_train,y_train)

C:\Users\91944\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\91944\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [49]:
y_test[:5]

Attrition
442           0
1091          0
981           1
785           0
1332          1

In [51]:
y_pred=logr.predict(x_test)
y_pred[:5]

array([0, 0, 0, 0, 0])

In [54]:
from sklearn.metrics import confusion_matrix,classification_report
confusion_matrix(y_pred,y_test)

array([[245,  49],
       [  0,   0]], dtype=int64)

In [55]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       1.00      0.83      0.91       294
           1       0.00      0.00      0.00         0

    accuracy                           0.83       294
   macro avg       0.50      0.42      0.45       294
weighted avg       1.00      0.83      0.91       294



C:\Users\91944\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [56]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()
dtc.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [57]:
y_pred=dtc.predict(x_test)

In [58]:
y_pred[:5]

array([0, 0, 0, 0, 0])

In [59]:
y_test[:5]

Attrition
442           0
1091          0
981           1
785           0
1332          1

In [62]:
from sklearn.metrics import r2_score
r2_score(y_pred,y_test)

-0.8673780487804879

In [64]:
y_pred_train=dtc.predict(x_train)
r2_score(y_pred_train,y_train)

1.0

In [65]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()
rfc.fit(x_train,y_train)

C:\Users\91944\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\91944\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [68]:
from sklearn.metrics import r2_score
yu=rfc.predict(x_test)
r2_score(yu,y_test)

-2.0580291970802915

In [69]:
y_pred_train=rfc.predict(x_train)
r2_score(y_train,y_pred_train)

0.8353863381858903

In [70]:
from sklearn.neighbors import KNeighborsClassifier 
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)

C:\Users\91944\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [71]:
y_test[:5]

Attrition
442           0
1091          0
981           1
785           0
1332          1

In [72]:
y_pred=knn.predict(x_test)
y_pred[:5]

array([0, 0, 0, 0, 0])

In [74]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8061224489795918

In [76]:
y_train_pred=knn.predict(x_train)
y_train_pred[:5]

array([0, 0, 0, 0, 1])

In [77]:
accuracy_score(y_train,y_train_pred)

0.8537414965986394

In [78]:
from sklearn.metrics import confusion_matrix
confusion_matrix=confusion_matrix(y_train,y_train_pred)
print(confusion_matrix)

[[970  18]
 [154  34]]


In [82]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.83      0.96      0.89       245
           1       0.10      0.02      0.03        49

    accuracy                           0.81       294
   macro avg       0.47      0.49      0.46       294
weighted avg       0.71      0.81      0.75       294



In [83]:
from sklearn.model_selection import GridSearchCV
grid_param={
    'criterion':['gini','entropy'],'max_depth': [1,2,3]
}
grid_search=GridSearchCV(estimator=dtc,param_grid=grid_param,cv=5,n_jobs=-1)
grid_search.fit(x_train,y_train)

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=DecisionTreeClassifier(class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort=False, random_state=None,
                                              splitter='best'),
             iid='warn', n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [1, 2, 3]},
             pre_dispatch='2*

In [84]:
grid_search.best_params_

{'criterion': 'gini', 'max_depth': 1}

In [85]:
dtc_hyper=DecisionTreeClassifier(criterion='entropy',max_depth=5)
dtc_hyper.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=5,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [86]:
y_pred_hyper=dtc_hyper.predict(x_test)
accuracy_score(y_test,y_pred_hyper)

0.8129251700680272