In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
data=pd.read_csv('EmployeeAttrition.csv')

In [3]:
data.head()

Education JobInvolvement  JobLevel  DailyRate(USD)  MonthlyIncome(USD)  \
0        College           High         2            1102              5993.0   
1  Below College         Medium         2             279              5130.0   
2        College         Medium         1            1373              2090.0   
3         Master           High         1            1392              2909.0   
4  Below College           High         1             591              3468.0   

   NoofCompaniesWorked  TotalWorkingYears  YearsAtCompany  YearsInCurrentRole  \
0                    8                  8               6                   4   
1                    1                 10              10                   7   
2                    6                  7               0                   0   
3                    1                  8               8                   7   
4                    9                  6               2                   2   

   YearsSinceLastPromotion  YearsWithCurrentManager  TrainingTimesLastYear  \
0                        0                        5                      0   
1                        1                        7                      3   
2                        0                        0                      3   
3                        3                        0                      3   
4                        2                        2                      3   

  PerformanceRating Attrition  
0         Excellent       Yes  
1       Outstanding        No  
2         Excellent       Yes  
3         Excellent        No  
4         Excellent        No

In [130]:
# columns that are continous/numerical and categorical

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 14 columns):
Education                  1470 non-null object
JobInvolvement             1466 non-null object
JobLevel                   1470 non-null int64
DailyRate(USD)             1470 non-null int64
MonthlyIncome(USD)         1466 non-null float64
NoofCompaniesWorked        1470 non-null int64
TotalWorkingYears          1470 non-null int64
YearsAtCompany             1470 non-null int64
YearsInCurrentRole         1470 non-null int64
YearsSinceLastPromotion    1470 non-null int64
YearsWithCurrentManager    1470 non-null int64
TrainingTimesLastYear      1470 non-null int64
PerformanceRating          1470 non-null object
Attrition                  1470 non-null object
dtypes: float64(1), int64(9), object(4)
memory usage: 160.9+ KB


In [5]:
data.isnull().sum()

Education                  0
JobInvolvement             4
JobLevel                   0
DailyRate(USD)             0
MonthlyIncome(USD)         4
NoofCompaniesWorked        0
TotalWorkingYears          0
YearsAtCompany             0
YearsInCurrentRole         0
YearsSinceLastPromotion    0
YearsWithCurrentManager    0
TrainingTimesLastYear      0
PerformanceRating          0
Attrition                  0
dtype: int64

In [6]:
data['MonthlyIncome(USD)']=data['MonthlyIncome(USD)'].fillna(data['MonthlyIncome(USD)'].median())
data['JobInvolvement'].fillna(data['JobInvolvement'].mode()[0],inplace=True)

In [7]:
data

Education JobInvolvement  JobLevel  DailyRate(USD)  \
0           College           High         2            1102   
1     Below College         Medium         2             279   
2           College         Medium         1            1373   
3            Master           High         1            1392   
4     Below College           High         1             591   
5           College           High         1            1005   
6          Bachelor      Very High         1            1324   
7     Below College           High         1            1358   
8          Bachelor           High         3             216   
9          Bachelor           High         2            1299   
10         Bachelor      Very High         1             809   
11          College         Medium         2             153   
12    Below College           High         1             670   
13          College           High         1            1346   
14         Bachelor         Medium         1             103   
15           Master      Very High         3            1389   
16          College      Very High         1             334   
17          College      Very High         1            1123   
18           Master         Medium         4            1219   
19         Bachelor           High         1             371   
20          College      Very High         2             673   
21           Master         Medium         1            1218   
22           Master           High         3             419   
23          College           High         1             391   
24    Below College           High         1             699   
25         Bachelor           High         5            1282   
26    Below College           High         1            1125   
27           Master           High         2             691   
28           Master           High         3             477   
29           Master           High         5             705   
...             ...            ...       ...             ...   
1440        College           High         2             688   
1441         Master           High         2             667   
1442         Master           High         1            1092   
1443       Bachelor           High         5             300   
1444        College           High         1             310   
1445         Master         Medium         4             582   
1446       Bachelor         Medium         2             704   
1447         Master            Low         2             301   
1448       Bachelor         Medium         2             930   
1449       Bachelor           High         1             529   
1450         Master           High         3            1146   
1451        College           High         2             345   
1452         Master           High         2             878   
1453         Master         Medium         2            1120   
1454       Bachelor           High         2             374   
1455         Master         Medium         1            1322   
1456         Master           High         2            1199   
1457         Master           High         1            1194   
1458         Master            Low         1             287   
1459        College         Medium         2            1378   
1460         Master         Medium         1             468   
1461       Bachelor         Medium         3             410   
1462  Below College         Medium         4             722   
1463       Bachelor           High         2             325   
1464       Bachelor         Medium         1            1167   
1465        College      Very High         2             884   
1466  Below College         Medium         3             613   
1467       Bachelor      Very High         2             155   
1468       Bachelor         Medium         2            1023   
1469       Bachelor      Very High         2             628   

      MonthlyIncome(USD)  NoofCompaniesWo

In [8]:
data.head()

Education JobInvolvement  JobLevel  DailyRate(USD)  MonthlyIncome(USD)  \
0        College           High         2            1102              5993.0   
1  Below College         Medium         2             279              5130.0   
2        College         Medium         1            1373              2090.0   
3         Master           High         1            1392              2909.0   
4  Below College           High         1             591              3468.0   

   NoofCompaniesWorked  TotalWorkingYears  YearsAtCompany  YearsInCurrentRole  \
0                    8                  8               6                   4   
1                    1                 10              10                   7   
2                    6                  7               0                   0   
3                    1                  8               8                   7   
4                    9                  6               2                   2   

   YearsSinceLastPromotion  YearsWithCurrentManager  TrainingTimesLastYear  \
0                        0                        5                      0   
1                        1                        7                      3   
2                        0                        0                      3   
3                        3                        0                      3   
4                        2                        2                      3   

  PerformanceRating Attrition  
0         Excellent       Yes  
1       Outstanding        No  
2         Excellent       Yes  
3         Excellent        No  
4         Excellent        No

In [9]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
print(data["Education"].value_counts())
data['Education']=le.fit_transform(data['Education'])
print(data['Education'].value_counts())

Bachelor         572
Master           398
College          282
Below College    170
Doctor            48
Name: Education, dtype: int64
0    572
4    398
2    282
1    170
3     48
Name: Education, dtype: int64


In [10]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
print(data['JobInvolvement'].value_counts())
data['JobInvolvement']=le.fit_transform(data['JobInvolvement'])
print(data['JobInvolvement'].value_counts())

High         871
Medium       373
Very High    144
Low           82
Name: JobInvolvement, dtype: int64
0    871
2    373
3    144
1     82
Name: JobInvolvement, dtype: int64


In [11]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
print(data['PerformanceRating'].value_counts())
data['PerformanceRating']=le.fit_transform(data['PerformanceRating'])
print(data['PerformanceRating'].value_counts())

Excellent      1244
Outstanding     226
Name: PerformanceRating, dtype: int64
0    1244
1     226
Name: PerformanceRating, dtype: int64


In [12]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
print(data['Attrition'].value_counts())
data['Attrition']=le.fit_transform(data['Attrition'])
print(data['Attrition'].value_counts())

No     1233
Yes     237
Name: Attrition, dtype: int64
0    1233
1     237
Name: Attrition, dtype: int64


In [13]:
data.head()

Education  JobInvolvement  JobLevel  DailyRate(USD)  MonthlyIncome(USD)  \
0          2               0         2            1102              5993.0   
1          1               2         2             279              5130.0   
2          2               2         1            1373              2090.0   
3          4               0         1            1392              2909.0   
4          1               0         1             591              3468.0   

   NoofCompaniesWorked  TotalWorkingYears  YearsAtCompany  YearsInCurrentRole  \
0                    8                  8               6                   4   
1                    1                 10              10                   7   
2                    6                  7               0                   0   
3                    1                  8               8                   7   
4                    9                  6               2                   2   

   YearsSinceLastPromotion  YearsWithCurrentManager  TrainingTimesLastYear  \
0                        0                        5                      0   
1                        1                        7                      3   
2                        0                        0                      3   
3                        3                        0                      3   
4                        2                        2                      3   

   PerformanceRating  Attrition  
0                  0          1  
1                  1          0  
2                  0          1  
3                  0          0  
4                  0          0

In [14]:
# dependant and independant

In [15]:
x2=data.iloc[:,[0,1,2,4,5,6,11,12]]
x2.head()

Education  JobInvolvement  JobLevel  MonthlyIncome(USD)  \
0          2               0         2              5993.0   
1          1               2         2              5130.0   
2          2               2         1              2090.0   
3          4               0         1              2909.0   
4          1               0         1              3468.0   

   NoofCompaniesWorked  TotalWorkingYears  TrainingTimesLastYear  \
0                    8                  8                      0   
1                    1                 10                      3   
2                    6                  7                      3   
3                    1                  8                      3   
4                    9                  6                      3   

   PerformanceRating  
0                  0  
1                  1  
2                  0  
3                  0  
4                  0

In [16]:
y=data.iloc[:,[13]]
y.head()

Attrition
0          1
1          0
2          1
3          0
4          0

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x2,y,test_size=0.2,random_state=0)

In [18]:
print(x_train.shape)
print(x_test.shape)

(1176, 8)
(294, 8)


In [19]:
print(y_train.shape)
print(y_test.shape)

(1176, 1)
(294, 1)


In [20]:
# Feature selection

In [21]:
from sklearn.feature_selection import mutual_info_classif
mi=mutual_info_classif(x_train,y_train)
mi

C:\Users\91944\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0.        , 0.        , 0.03500464, 0.04142041, 0.02807788,
       0.02661593, 0.00110606, 0.01061491])

In [22]:
MI=pd.Series(mi)
MI.index=x_train.columns
MI.sort_values(ascending=False)

MonthlyIncome(USD)       0.041420
JobLevel                 0.035005
NoofCompaniesWorked      0.028078
TotalWorkingYears        0.026616
PerformanceRating        0.010615
TrainingTimesLastYear    0.001106
JobInvolvement           0.000000
Education                0.000000
dtype: float64

In [23]:
# Model Building 

In [77]:
from sklearn.linear_model import LogisticRegression
logr=LogisticRegression()
logr.fit(x_train,y_train)

C:\Users\91944\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\91944\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [25]:
y_test[:5]

Attrition
442           0
1091          0
981           1
785           0
1332          1

In [26]:
y_pred=logr.predict(x_test)
y_pred[:5]

array([0, 0, 0, 0, 0])

In [27]:
from sklearn.metrics import confusion_matrix,classification_report
confusion_matrix(y_pred,y_test)

array([[244,  49],
       [  1,   0]], dtype=int64)

In [28]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       1.00      0.83      0.91       293
           1       0.00      0.00      0.00         1

    accuracy                           0.83       294
   macro avg       0.50      0.42      0.45       294
weighted avg       0.99      0.83      0.90       294



In [74]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()
dtc.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [30]:
y_pred=dtc.predict(x_test)

In [31]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score


In [32]:
accuracy_score(y_pred,y_test)

0.7482993197278912

In [33]:
confusion_matrix(y_pred,y_test)

array([[210,  39],
       [ 35,  10]], dtype=int64)

In [34]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.84      0.86      0.85       245
           1       0.22      0.20      0.21        49

    accuracy                           0.75       294
   macro avg       0.53      0.53      0.53       294
weighted avg       0.74      0.75      0.74       294



In [35]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()
rfc.fit(x_train,y_train)

C:\Users\91944\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\91944\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [36]:
y_test[:5]

Attrition
442           0
1091          0
981           1
785           0
1332          1

In [37]:
y_pred=rfc.predict(x_test)
y_pred[:5]

array([0, 0, 0, 0, 1])

In [38]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
accuracy_score(y_test,y_pred)

0.8299319727891157

In [39]:
confusion_matrix(y_test,y_pred)

array([[240,   5],
       [ 45,   4]], dtype=int64)

In [40]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.84      0.98      0.91       245
           1       0.44      0.08      0.14        49

    accuracy                           0.83       294
   macro avg       0.64      0.53      0.52       294
weighted avg       0.78      0.83      0.78       294



In [41]:
from sklearn.neighbors import KNeighborsClassifier 
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)

C:\Users\91944\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [42]:
y_test[:5]

Attrition
442           0
1091          0
981           1
785           0
1332          1

In [43]:
y_pred=knn.predict(x_test)
y_pred[:5]

array([0, 0, 0, 0, 0])

In [44]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8129251700680272

In [45]:
y_train_pred=knn.predict(x_train)
y_train_pred[:5]

array([0, 0, 0, 0, 1])

In [46]:
accuracy_score(y_train,y_train_pred)

0.8494897959183674

In [47]:
from sklearn.metrics import confusion_matrix
confusion_matrix=confusion_matrix(y_train,y_train_pred)
print(confusion_matrix)

[[966  22]
 [155  33]]


In [48]:
from sklearn.metrics import confusion_matrix
confusion_matrix=confusion_matrix(y_train,y_train_pred)
print(confusion_matrix)

[[966  22]
 [155  33]]


In [49]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.84      0.96      0.90       245
           1       0.25      0.06      0.10        49

    accuracy                           0.81       294
   macro avg       0.54      0.51      0.50       294
weighted avg       0.74      0.81      0.76       294



In [79]:
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.svm import SVC 
svm = SVC() 
svm.fit(x_train, y_train) 

C:\Users\91944\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\91944\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [51]:
y_test[:10]

Attrition
442           0
1091          0
981           1
785           0
1332          1
501           0
1058          1
1253          0
751           0
122           1

In [52]:
y_pred=svm.predict(x_test)
y_pred[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [53]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8333333333333334

In [54]:
y_pred_train=svm.predict(x_train)
accuracy_score(y_train,y_pred_train)

0.9931972789115646

In [55]:
y_train_pred=svm.predict(x_train)
y_train_pred

array([0, 0, 0, ..., 0, 0, 0])

In [56]:
accuracy_score(y_train,y_train_pred)

0.9931972789115646

In [57]:
from collections import Counter as c
c(y_test)

Counter({'Attrition': 1})

In [58]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

[[245   0]
 [ 49   0]]
              precision    recall  f1-score   support

           0       0.83      1.00      0.91       245
           1       0.00      0.00      0.00        49

    accuracy                           0.83       294
   macro avg       0.42      0.50      0.45       294
weighted avg       0.69      0.83      0.76       294



C:\Users\91944\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [59]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(x_train,y_train)

C:\Users\91944\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None, var_smoothing=1e-09)

In [60]:
y_test[:5]

Attrition
442           0
1091          0
981           1
785           0
1332          1

In [61]:
y_pred=nb.predict(x_test)
y_pred[:5]

array([0, 0, 0, 0, 0])

In [62]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8129251700680272

In [63]:
y_train_pred=nb.predict(x_train)
y_train_pred

array([0, 0, 0, ..., 0, 0, 0])

In [64]:
accuracy_score(y_train,y_train_pred)

0.842687074829932

In [65]:
from collections import Counter as c
c(y_test)

Counter({'Attrition': 1})

In [66]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[237   8]
 [ 47   2]]


In [67]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.97      0.90       245
           1       0.20      0.04      0.07        49

    accuracy                           0.81       294
   macro avg       0.52      0.50      0.48       294
weighted avg       0.73      0.81      0.76       294



In [68]:
# Hyper Tuning

In [69]:
from sklearn.model_selection import GridSearchCV
grid_param={ 
    'criterion':['gini','entropy'],
    'max_depth' : [ 5,6,7] 
}
grid_search=GridSearchCV(estimator=dtc,param_grid=grid_param,cv=5,n_jobs=-1)
grid_search.fit(x_train,y_train)

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=DecisionTreeClassifier(class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort=False, random_state=None,
                                              splitter='best'),
             iid='warn', n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [5, 6, 7]},
             pre_dispatch='2*

In [70]:
grid_search.best_params_

{'criterion': 'entropy', 'max_depth': 6}

In [71]:
dtc_hyper=DecisionTreeClassifier(criterion='entropy',max_depth=5)
dtc_hyper.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=5,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [72]:
y_pred_hyper=dtc_hyper.predict(x_test)
accuracy_score(y_test,y_pred_hyper)

0.8163265306122449

In [80]:
confusion_matrix(y_pred,y_test)

array([[237,  47],
       [  8,   2]], dtype=int64)

In [81]:
confusion_matrix(y_pred_hyper,y_test)

array([[238,  47],
       [  7,   2]], dtype=int64)